# -*- coding: utf-8 -*-
"""KNN_Hardcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8HYnJDkZdvcWjbS3DXEwk9CFdoMIH90

# K-Nearest Neighbour Classification

---


This is a KNN hardcode with python. Pandas library is used to import and load the data, and NumPy is used for algebric operations.

The Iris dataset from UCI database is used which has 150 instances. It has 4 features and classifies it between 3 flowers.
"""

# fetching the data from uci datasets
!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo
iris = fetch_ucirepo(id=53)

# importing essential libs
import numpy as np
import pandas as pd

# loading the data
df = iris.data.original

# shuffling the data
df = df.sample(frac=1).reset_index(drop=True)

# splitting the data into 130 training data and 20 testing data
m,n = df.shape

df_train = df[0: 130]
y_train = df_train['class']
X_train = df_train.drop('class', axis=1)

df_test = df[130 : n]
y_test = df_train['class']
X_test = df_train.drop('class', axis=1)
X_train

# converting the data to array

X_train = np.array(X_train)
y_train = np.array(y_train)
X_test = np.array(X_test)
y_test = np.array(y_test)
m_train, n_train = X_train.shape
m_test, n_test = X_test.shape
X_train

# Defining distance
def distance(x1,x2):
  return np.sqrt(np.sum((np.array(x1)-np.array(x2))**2))   #Here we are using euclidian distance

#testing 1 instance for error check
distance(X_train[0], X_train[1])

# Creating the KNN function
def KNN(x1, k):

  list = []  #to hold classes of the neighbours
  d_list = []   #to hold distances to the neighbours

  for i in range(0,130):
    d = distance(np.array(x1), X_train[i])

    # adding the classes and distances into the lists till they contain k elements
    if len(list)<k:
      list.append(y_train[i])
      d_list.append(d)

    else:
      # check if the current points is closer than others in the list
      for j in range(0,k):
        if d<d_list[j]:
          list.append(y_train[i])
          d_list.append(d)

          # removing the farthest neighbours so that only k neighbours are in the list
          list.pop(d_list.index(max(d_list)))
          d_list.pop(d_list.index(max(d_list)))

  # to count the occurance of each class in the list
  counts = {}

  for i in list:
    if i in counts:
      counts[i] += 1
    else:
      counts[i] = 1

  return max(counts)

KNN(X_test[0], 5)

# comparing builtin KNN of sklearn with my knn function
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()

knn.fit(X_train, y_train)

knn.predict([X_test[0]])